version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "build(deps)"
    groups:
      go-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "build(actions)"
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
